# Generated by Django 5.0.6 on 2024-08-01 03:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base',
            new_name='BaseEng',
        ),
        migrations.RenameModel(
            old_name='UserWord',
            new_name='UserWordEng',
        ),
    ]
