# Generated by Django 5.0.6 on 2024-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkwordseng',
            name='word_rus',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='checkwordsger',
            name='word_rus',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
